{% set name = "asttokens" %}
{% set version = "2.0.1" %}
{% set sha256 = "8ba21b5ef63dc0bbae49ccd50badef00469c4f17dbc5ef6db8add900a2f991f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - asttokens

about:
  home: https://github.com/gristlabs/asttokens
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The asttokens module annotates Python abstract syntax trees (ASTs) with the positions of tokens and text in the source code that generated them.'
  dev_url: https://github.com/gristlabs/asttokens

extra:
  recipe-maintainers:
    - dopplershift
