{% set name = "asttokens" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0dcd8baa8d62b0c1d118b399b2ddba3c4aff271d0d7a9e0d4c1681c79035bbc7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}

requirements:
  host:
    - python
    - pip
    - setuptools >=44
    - setuptools_scm >=3.4.3
    - toml
    - wheel
  run:
    - python
  run_constrained:
    - astroid >=2, <4

test:
  imports:
    - asttokens
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/gristlabs/asttokens
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The asttokens module annotates Python abstract syntax trees (ASTs) with the positions of tokens and text in the source code that generated them.
  description: |
    The asttokens module annotates Python abstract syntax trees (ASTs) with the positions of tokens and text in the source code that generated them.
    It provides a way to access the original source code from the AST, which can be useful for debugging, code analysis, and other tasks.
  dev_url: https://github.com/gristlabs/asttokens
  doc_url: https://github.com/gristlabs/asttokens

extra:
  recipe-maintainers:
    - dopplershift
