travis:
  secure:
    BINSTAR_TOKEN: GPojqlJu14+mKFFWH/EEIhpwHgM5mCvggRvEQTOYABd9faP1e1nrGoh2ROdf+igFjtete7ilLbM7ARbyNsFZb4TfSNxnHyLGcD8TkzLT45N95DecTONQIOyYr+1y/sloe9fvEyBgrAY284dBZTQ47goHt7j2mQ7CHzfUZ6iSjCbvwCw6jQelXCwBvA6Gf5eDuD0/X8xFvwiEUTiyd5qUA8ULRdd0bYhvC7rRZv29McKIyKnoAKcOEPscwZIlEFRchMna9HCL6abA5fkNeizCKNJ7jl4wuqT6PyCHo6ZsPgNY5xXZHuGxcg7o+bIC/tQZHLKj9p6vsuHiINwpUQXqr0HpEoQSxpf4jmYVaRrRUh8y+AcsrhlNxsTjEgq1lN4zvMMAfK/yCfWfOkv0ze+gDA+KLfwJoctMyS0mKcG/QS7G9Blkpsd2na/7fSD+g/l5KvB8SkrDrZyczujU5SuuLpUvFTikdoZ1x1/RpH31ybChJPJPne52baphI4qi+uxjglnM/DwSh7DFxQUfqOxtBbJL1vrVCm0o71bTWwIrI0Dpgwq2Tk6jW2n4sH6LWjEny5z550kSUJJ9ErH6ygCoTOspOLOWXf8kCT0nh9w6BBodhv5ssg8CtJriikmO2PdELDXwlzXe8mxTEMipe2+w9FQj/8UXOA4pwUlVmdbGtso=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
