travis:
  secure:
    BINSTAR_TOKEN: kh7JwgiAbSabllEfmAouXNg9kziphTsW8cJqP3X5lJAsIFIOLAv69YDlLYetkxXeUmMa6MJsjZH8kT9OQTDJ0U6BOgkAmSqNpZU/uuNZ6amq1jtsFU7fPqqqkGYmg7Mr/61LeTBDjydUNsdzMS1eH+DISzXyYSiSaMyAPzgJXx+4w6EH20O6QAR+749JNiND+MHvaP+ALwzvo28XhKHSTD53dzJsumez7+2ubcgS4oeub6qwdpSTRPKL5kfi9pOa+3X3LZlxtug4k82Ad/rRyPZMG8RQB2QyElf4Vr5f4gGL3QGivs7E2VpqNA6p5mbAqP837BZ4hW8cH1gvTiMjM691iHqfYphHKEnOkMIrc69i1SQQUwf5Xo2qBBohRftbOAClq/YxO7JdUJVo/3dZA3M+fTUSNT2eKgxSy+Oxhue9IHT+/iO6n9xpSYojOQdARTh0Li0s7TAY5RwBu+5UmYoIe5er6mHYKHMtxN+LoynHciay6wcykW7q+ttA4W2y0WXAS3hSDS0rnjgu13T4tSGxgMt0D/A3g5p206coJVEYno8yu03AIgLs6nfG8ypkv3YDNBMaM0h8T5/u1pvgNS0o0+7a1Fx+l5DpH9Fkn4/OWWn5X4JWZaolGbulycLH52E6t/70xzBQ+wvn3XMbHTZSWmo/Xc+ENYZ443uegpw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
